- name: Atualização dos pacotes do S.O
  yum:
    name: "*"
    state: latest
    
- name: Instalação do Git Client
  yum:
    name: "git"
    state: latest    

- name: Configurar hosts lab ansible    
  lineinfile: 
    dest: /etc/hosts 
    state: present
    line: "{{item}}" #item é o valor de cada item do array
  with_items:         #Iteração sobre o array
    - 192.168.1.2 control-node
    - 192.168.1.3 app01
    - 192.168.1.4 bd01    