mysql_root_password: devops
mysql_databases:
  - name: "notes"
    enconding: utf8
    collation: utf8_general_ci
mysql_users:
  - name: notesapp
    host: "%"   #% significa todos os hosts
    password: devops
    priv: "notes.*:ALL" #Libera todas as tabelas do banco notes