---
- name: Configurar servidor de banco de dados
  hosts: db01

  user: vagrant
  become: yes     #Para executar como root
  vars_files:
    - vars/main.yml
  vars:
    - dbname: "db01"
    - dbusername: "root"
    - dbpassword: "devops"
  tasks:
    - name: Configurar hosts lab ansible    
      lineinfile: 
        dest: /etc/hosts 
        state: present
        line: "{{item}}" #item é o valor de cada item do array
      with_items:         #Iteração sobre o array
        - 192.168.1.2 control-node
        - 192.168.1.3 app01
        - 192.168.1.4 bd01
  roles:
  - configuracao-default-so
  - role: geerlingguy.mysql
    