---
- name: Configurar servidor de banco de dados
  hosts: db01

  user: vagrant
  become: yes     #Para executar como root
  vars_files:
    - vars/main.yml
  vars:
    - dbname: "db01"
    - dbusername: "root"
    - dbpassword: "devops"
  
  roles:
    - configuracao-default-so
    - role: geerlingguy.mysql
    